-- MySQL Script generated by MySQL Workbench
-- sáb 14 abr 2018 14:32:43 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema teste_api
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema teste_api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teste_api` DEFAULT CHARACTER SET utf8 ;
USE `teste_api` ;

-- -----------------------------------------------------
-- Table `teste_api`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teste_api`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `teste_api`.`Cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste_api`.`Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teste_api`.`Vendedor` ;

CREATE TABLE IF NOT EXISTS `teste_api`.`Vendedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste_api`.`Venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teste_api`.`Venda` ;

CREATE TABLE IF NOT EXISTS `teste_api`.`Venda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clienteId` INT NOT NULL,
  `data` DATE NOT NULL,
  `vendedorId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Venda_Cliente1_idx` (`clienteId` ASC),
  INDEX `fk_Venda_Vendedor1_idx` (`vendedorId` ASC),
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`clienteId`)
    REFERENCES `teste_api`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Vendedor1`
    FOREIGN KEY (`vendedorId`)
    REFERENCES `teste_api`.`Vendedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste_api`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teste_api`.`Produto` ;

CREATE TABLE IF NOT EXISTS `teste_api`.`Produto` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste_api`.`Venda_has_Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teste_api`.`Venda_has_Produto` ;

CREATE TABLE IF NOT EXISTS `teste_api`.`Venda_has_Produto` (
  `Venda_id` INT NOT NULL,
  `Produto_id` INT NOT NULL,
  PRIMARY KEY (`Venda_id`, `Produto_id`),
  INDEX `fk_Venda_has_Produto_Produto1_idx` (`Produto_id` ASC),
  INDEX `fk_Venda_has_Produto_Venda_idx` (`Venda_id` ASC),
  CONSTRAINT `fk_Venda_has_Produto_Venda`
    FOREIGN KEY (`Venda_id`)
    REFERENCES `teste_api`.`Venda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_has_Produto_Produto1`
    FOREIGN KEY (`Produto_id`)
    REFERENCES `teste_api`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
